### ISSUE TITLE
Wondering where the forms responses will be save and how to retrieve them, How to use regular expression matches and data validations?

### ISSUE THREAD

**Issue by myaseen208** [jlgraves-ubc/forms#3]
I'm trying your Quarto extension forms as given [here](https://myaseen208.com/misc/forms.html). I've few questions about forms:

   1.  Wondering where the forms responses will be save and how to retrieve them.
    2. How to use regular expression matches and data validations?
    3. Wondering if it is possible to allow the submission of form to predefined user.

**Comment by jlgraves-ubc** [comment]
Hi,

1.  Quarto's website projects are a static site generator, so I built the `forms` extension to be a static element as well.  This means that it only provides (generates) the HTML front-end for a form.  You have to provide the form-handler yourself, based on your site's design - basically, you need a back-end, and then use the extension to hook it up to the form's submit action.  Only the last part is handled by the forms extension.

In other words, you need to define what happens when the "submit" button is clicked by the user.  This can be done in a number of ways - for instance, in the `example.qmd` file, I have it call a Javascript function:

```
function submit() { alert("Submitted!"); }
```

The `action` attribute of the form specifies what happens when the form is submitted, and where the form responses go.  None of this is handled natively by the `forms` extension, since it is not something Quarto (as a static site) can handle - you need some kind of backend to handle it.

One of the most common ways is to set up a PHP page on your server that handles the form submissions and adds them to a database, but there are innumerable backend solutions out like (I like Strapi, but you can look at [this site](https://jamstack.org/headless-cms/) for a bunch of options).  You can also have it handled by Javascript, but then the script still needs to do something with the form response.

Here's W3School's minimal example: 

https://www.w3schools.com/html/html_forms_attributes.asp
https://www.w3schools.com/php/php_forms.asp

This also addresses your third question; users and form response attribution is backend - you've define that in your form handler as well.

2.  Related to (1), I haven't implemented any of the data validation beyond what you see in the options.  There **are** more options for data validation for form inputs available in HTML5, but they're nasty to implement... so I didn't.  I figured that since you can handle this with Javascript or PHP on form submit it's not worth trying to make a general implementation at the moment - for example: 

https://stackoverflow.com/questions/7410063/how-can-i-listen-to-the-form-submit-event-in-javascript

Maybe for version 2.0.

**Comment by JOduMonT** [comment]
> 1. Wondering where the forms responses will be save and how to retrieve them.

@jlgraves-ubc is `mailto:myemailincleartext@gmail.com` possible as an action?

---
form:
  action: "mailto:myemailincleartext@gmail.com"
---

### if yes, what about with an encoded email?

---
form:
  action: "mailto:&#109;&#121;&#101;&#109;&#97;&#105;&#108;&#105;&#110;&#99;&#108;&#101;&#97;&#114;&#116;&#101;&#120;&#116;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;"
---

**Comment by jlgraves-ubc** [comment]
Hi @JOduMonT 

I'm not sure.  Theoretically, you can do this ([see here, for example](https://www.tutorialspoint.com/How-do-we-send-an-email-using-HTML-forms)). 

* The only reason I am not sure is because I am not sure what the default encoding type is, but I think this will work.  If you decide to go this route, try it and let me know.   There's currently no way to change the encoding type, but I think that could be added fairly easily.

However, the bigger picture reason I didn't test this is because HTML `mailto` form actions are generally not recommend - they trigger an external email client, which is not user friendly, and are not compatible with all browsers or systems.
